networks:
  creadit_assigner:

volumes:
  mssql_data:
    driver: local

services:

  credit_assigner:
    image: dory15/credit_assigner:v1.0.0
    environment:
      ENV: "prod"
      DB_STRING: "sqlserver://sa:pass@sqlserver:1433?database=credit_assigner"
      PORT: "3000"
      ACCEPT_EULA: Y
      SA_PASSWORD: "pass"
    ports:
      - "3000:3000"
    container_name: creadit_assigner
    restart: always
    networks:
      - creadit_assigner

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "pass"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    hostname: sql1
    container_name: sql1
    restart: always
    networks:
      - creadit_assigner